#!/bin/bash

if groups | grep docker > /dev/null 2>&1; then
    DOCKER_BINARY=docker
else
    DOCKER_BINARY="sudo docker"
fi


${DOCKER_BINARY} buildx build --platform=linux/arm64  --progress=plain --load -t krita-appimage-2404 -t krita-appimage-2404:arm64 base-images/.

